<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/DZ_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [4]:
arr_even = np.arange(30, 71, 2)
print(arr_even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [3]:
arr02_2 = np.random.randint(0, 1, 10)
print('Масив 10 чисел:', arr02_2)

Масив 10 чисел: [0 0 0 0 0 0 0 0 0 0]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [18]:
n = 2
arr = np.random.randint(1, 10, (n+2, n+2))
print(arr)

a = np.hstack((np.zeros((arr.shape[0], 1)), arr, np.zeros((arr.shape[0], 1))))
result_array = np.vstack((np.zeros((1, a.shape[1])), a, np.zeros((1, a.shape[1]))))
print("result: ")
result_array


[[2 3 6 8]
 [6 3 5 3]
 [1 8 6 8]
 [5 5 5 4]]
result: 


array([[0., 0., 0., 0., 0., 0.],
       [0., 2., 3., 6., 8., 0.],
       [0., 6., 3., 5., 3., 0.],
       [0., 1., 8., 6., 8., 0.],
       [0., 5., 5., 5., 4., 0.],
       [0., 0., 0., 0., 0., 0.]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [22]:
print('Type:', result_array.dtype)
result_array_changed_type = result_array.astype(np.int32, copy=False)
print(result_array_changed_type)
print('Type:', result_array_changed_type.dtype)

Type: float64
[[0 0 0 0 0 0]
 [0 2 3 6 8 0]
 [0 6 3 5 3 0]
 [0 1 8 6 8 0]
 [0 5 5 5 4 0]
 [0 0 0 0 0 0]]
Type: int32


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [27]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
x_replaced = np.where(x == var, -1, np.where(x > var, -1, -1))
print(x_replaced)


[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [28]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1

print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [30]:
import numpy as np
X = np.random.rand(4, 6)
# print(X)
print(X.reshape((3, 8)))

[[0.71554742 0.79837286 0.64369507 0.06859041 0.3138075  0.7086242
  0.74173017 0.85083636]
 [0.2891046  0.88908882 0.70665956 0.44478187 0.88993737 0.9186981
  0.27375725 0.06497908]
 [0.69049435 0.18896878 0.21393547 0.29685946 0.56745093 0.12917792
  0.31321536 0.98193025]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [34]:
arr_3_4 = np.random.rand(3, 4)
arr_3_4

mean_per_column = np.mean(arr_3_4, axis=0)
print("MEAN: ")
mean_per_column

MEAN: 


array([0.44849502, 0.61879843, 0.53768709, 0.47715903])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [38]:
import numpy as np

matrix = np.random.random((5, 6))

# round
matrix_rounded = np.around(matrix, decimals=1)
matrix_rounded
# sort
sorted_matrix = matrix_rounded[:, matrix_rounded[0, :].argsort()]
sorted_matrix


array([[0.1, 0.2, 0.4, 0.5, 0.6, 0.9],
       [0.5, 0.4, 0.3, 0.9, 0.5, 1. ],
       [0.6, 0.4, 0.1, 1. , 1. , 0.8],
       [0.3, 0.6, 0.1, 0.6, 0.7, 0.5],
       [0. , 0.6, 0.6, 0.6, 0.4, 1. ]])

#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [39]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
print(X[(3 < X) & (X < 6 )])

[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [42]:
matrix = np.random.random((5, 6))

matrix_normalized = (matrix - matrix.min(axis=0)) / (matrix.max(axis=0) - matrix.min(axis=0))

print(matrix_normalized)

[[0.2847562  0.63260873 0.         0.46133863 0.17307543 0.8227667 ]
 [0.00619958 0.04654285 0.43018107 0.13528798 0.9922859  0.        ]
 [0.         0.6723029  0.83110101 0.05932132 0.05097984 0.25931976]
 [0.88738611 0.         1.         0.         0.         0.11551232]
 [1.         1.         0.01805522 1.         1.         1.        ]]
