<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:

import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [3]:
x = np.arange(1, 13)
print(f'{x = }')
print(f'{x.shape = }')
print(f'{x.dtype = }')

x = array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
x.shape = (12,)
x.dtype = dtype('int64')


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [4]:
new_x = x.reshape((-1, 4))
new_x = new_x.astype(np.float32)

print(new_x.T)

[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [14]:
board = np.zeros((8, 8), dtype=np.int8)


board[::2, ::2] = 1
board[1::2, 1::2] = 1

board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.